---
title: "test - james - trees"
author: "James Ng (nj2208)"
date: "5/5/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(RNHANES)
library(caret)
library(rpart)
library(rpart.plot)
#library(glmnet)
#library(pls)
#library(splines)
#library(mgcv)
#library(pdp)
#library(earth)
#library(lasso2)
#library(mlbench)
#library(pROC)
#library(vip)
#library(AppliedPredictiveModeling)
#library(qwraps2)
library(arsenal)
#library(HH)
#library(summarytools)
#library(leaps)
library(ranger)
library(gbm)

knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
data_files <- nhanes_load_data(file_name = "DIQ_H", year = "2013-2014")

data_files <- data_files %>% 
  left_join(nhanes_load_data("HDL_H", "2013-2014"), by = "SEQN") %>%
  left_join(nhanes_load_data("INS_H", "2013-2014"), by = "SEQN") %>%
  left_join(nhanes_load_data("TRIGLY_H", "2013-2014"), by = "SEQN") %>% 
  left_join(nhanes_load_data("DEMO_H", "2013-2014"), by = "SEQN") %>% 
  left_join(nhanes_load_data("BMX_H", "2013-2014"), by = "SEQN") %>% 
  left_join(nhanes_load_data("OGTT_H", "2013-2014"), by = "SEQN") %>% 
  left_join(nhanes_load_data("BPX_H", "2013-2014"), by = "SEQN") %>% 
  left_join(nhanes_load_data("PAQ_H", "2013-2014"), by = "SEQN") %>% 
  left_join(nhanes_load_data("DPQ_H", "2013-2014"), by = "SEQN") %>% 
  left_join(nhanes_load_data("SLQ_H", "2013-2014"), by = "SEQN")
  
raw_data <- data_files %>% 
  select(SEQN, RIAGENDR, RIDAGEYR, RIDRETH3, BMXBMI, LBDHDD, LBDLDL, LBXTR, LBXIN, LBXGLT, BPXSY1, BPXDI1, BMXWAIST,  PAD680, DMDEDUC2, DMDMARTL, DPQ020, SLD010H,  DIQ010) 

raw_data <- raw_data[raw_data$DIQ010 != 3 & raw_data$DIQ010 != 7 & raw_data$DIQ010 != 9, ] %>%  mutate(RIAGENDR = as_factor(RIAGENDR), RIDRETH3 = as_factor(RIDRETH3),DMDEDUC2 = as_factor(DMDEDUC2), DMDMARTL = as_factor(DMDMARTL), DIQ010 = as_factor(DIQ010) ) %>% 
  drop_na(DIQ010) 
 
 colnames(raw_data) <- c("ID", "gender", "age", "race", "bmi", "hdl", "ldl", "triglyceride", "insulin", "glucose", "bp_systolic","bp_diastolic", "waist","lifestyle", "education", "married", "depression", "sleep", "diabetes") 
 
 contrasts(raw_data$diabetes)
 levels(raw_data$diabetes)[1] <- "yes"
 levels(raw_data$diabetes)[2] <- "no"
  contrasts(raw_data$diabetes)
  
## write.csv(raw_data, "final_data.csv")
```
# EDA

## Summary statistics

```{r}
#st_options(plain.ascii = FALSE,       
#           style = "rmarkdown", 
#           dfSummary.silent = TRUE,        
#           footnote = NA,          
#           subtitle.emphasis = FALSE)      

dfSummary(raw_data[,-1], valid.col = FALSE)

raw_data <- raw_data[-c(7:10)]
```

------------------------------------------------------------------------
Training data: NEW (5/7)

```{r}
# Missing data omitted
diabetes_data <- na.omit(raw_data) %>% 
  filter(married!="99") %>% 
  filter(married!="77") %>% 
  filter(education!="7") %>% 
  filter(education!="9") %>% 
  droplevels()

summary(diabetes_data)

set.seed(1)
trainRows <- createDataPartition(diabetes_data$diabetes, p = 0.8, list = FALSE)


# training data
x <- diabetes_data[trainRows ,-c(1, 15)]
xtree <- diabetes_data[trainRows ,-1]
y <- diabetes_data$diabetes[trainRows]

# test data
x2 <- diabetes_data[-trainRows ,-c(1, 15)]
y2 <- diabetes_data$diabetes[-trainRows]

```

```{r testing, eval=FALSE}
play = raw_data %>% 
  select(-glucose) %>% na.omit()

mid_eda = mid_naomit %>% 
  dplyr::mutate(gender = case_when(
    gender == 1 ~ "Male",
    gender == 2 ~ "Female",
    TRUE ~ NA_character_
  )) %>% 
  dplyr::mutate(race = case_when(
    race == 1 ~ "Mexican_American",
    race == 2	~ "Other_Hispanic",
    race == 3	~ "Non_Hispanic_White",
    race == 4	~ "Non_Hispanic_Black",
    race == 6	~ "Non_Hispanic_Asian",
    race == 7	~ "Other_Race_Including_MultiRacial",
    race == "."	~ "Missing",
    TRUE ~ NA_character_
  ))

```


```{r code chunks}
ctrl <- trainControl(method = "cv")

set.seed(1)
rpart.fit <- train(diabetes ~ . , 
                   diabetes_data[trainRows,-1], 
                   method = "rpart",
                   tuneGrid = data.frame(cp = exp(seq(-1,10, length = 500))),
                   trControl = ctrl)
ggplot(rpart.fit, highlight = TRUE)
rpart.plot(rpart.fit$finalModel)

cvconf = confusionMatrix(data = as.factor(oj_test_pred),
                reference = juice$Purchase[-jtrain],
                positive = "CH")

cverr = ((cvconf$table[1,2]+cvconf$table[2,1])/(cvconf$table[1,1]+cvconf$table[1,2]+cvconf$table[2,1]+cvconf$table[2,2]))

```

```{r}
## random forest in caret
ctrl = trainControl(method = "cv",
                     classProbs = TRUE, 
                     summaryFunction = twoClassSummary)

rf_grid = expand.grid(mtry = 1:17,
                       splitrule = "gini",
                       min.node.size = seq(from = 2, to = 10, by = 2))

set.seed(1)
rf_fit = train(diabetes ~ . ,
               diabetes_data[trainRows,-1], 
               method = "ranger",
               tuneGrid = rf_grid,
               metric = "ROC",
               trControl = ctrl)

ggplot(rf_fit, highlight = TRUE)


set.seed(1)
rf_final = ranger(diabetes ~ . ,
                     diabetes_data[trainRows,-1],
                     mtry = rf_fit$bestTune[[1]],
                     min.node.size = rf_fit$bestTune[[3]],
                     importance = "permutation",
                     scale.permutation.importance = TRUE) 

rf_table=rf_final$variable.importance
rf_final$prediction.error

rfclass_pred = predict(rf_final, data = diabetes_data[-trainRows,-1], type = "response")$predictions

rfconf = confusionMatrix(data = as.factor(rfclass_pred),
                reference = y2,
                positive = "yes")

rf_err = (rfconf$table[1,2]+rfconf$table[2,1])/(rfconf$table[1,1]+rfconf$table[1,2]+rfconf$table[2,1]+rfconf$table[2,2])
```


```{r}
gbm_grid = expand.grid(n.trees = c(0,1000,2000,3000,4000,5000,6000),
                        interaction.depth = 1:4,
                        shrinkage = c(0.001,0.003,0.005),
                        n.minobsinnode = c(1,10))

ctrl = trainControl(method = "cv")
                    
set.seed(1)
gbm_fit = train(diabetes ~ . , 
                 xtree, 
                 method = "gbm",
                 tuneGrid = gbm_grid,
                 trControl = ctrl,
                 verbose = FALSE)

ggplot(gbm_fit, highlight = TRUE)

#summary(gbm_fit$finalModel)
gbm_pred <- predict(gbm_fit, newdata = diabetes_data[-trainRows,], type = "prob")[,1]
gbm_test_pred = rep("no", length(gbm_pred))
gbm_test_pred[gbm_pred>0.5] = "yes"

gbmconf = confusionMatrix(data = as.factor(gbm_test_pred),
                reference = diabetes_data$diabetes[-trainRows],
                positive = "yes")

gbmconf$table

gbm_err = (gbmconf$table[1,2]+gbmconf$table[2,1])/(gbmconf$table[1,1]+gbmconf$table[1,2]+gbmconf$table[2,1]+gbmconf$table[2,2])

gbmA_grid <- expand.grid(n.trees = c(2000,3000,4000),
                         interaction.depth = 1:6,
                         shrinkage = c(0.001,0.003,0.005),
                         n.minobsinnode = 1)

ctrl = trainControl(method = "cv",
                    classProbs = TRUE)

set.seed(1)
gbmA_fit <- train(diabetes ~ . , 
                  diabetes_data, 
                  subset = trainRows, 
                  tuneGrid = gbmA_grid,
                  trControl = ctrl,
                  method = "gbm",
                  distribution = "adaboost",
                  metric = "ROC",
                  verbose = FALSE)

ggplot(gbmA_fit, highlight = TRUE)

gbmA_pred <- predict(gbmA_fit, newdata = diabetes_data[-trainRows,], type = "prob")[,1]
gbmA_test_pred = rep("no", length(gbmA_pred))
gbmA_test_pred[gbmA_pred>0.5] = "yes"

gbmAconf = confusionMatrix(data = as.factor(gbmA_test_pred),
                reference = diabetes_data$diabetes[-trainRows],
                positive = "yes")

gbmAconf$table

gbmA_err = (gbmAconf$table[1,2]+gbmAconf$table[2,1])/(gbmAconf$table[1,1]+gbmAconf$table[1,2]+gbmAconf$table[2,1]+gbmAconf$table[2,2])
```


```{r svml}
ctrl <- trainControl(method = "cv")

# kernlab
set.seed(1)
svml.fit <- train(diabetes ~ . , 
                  data = diabetes_data[trainRows,], 
                  method = "svmLinear",
                  preProcess = c("center", "scale"),
                  tuneGrid = data.frame(C = exp(seq(-4,4,len=20))),
                  trControl = ctrl)

#plot(svml.fit, highlight = TRUE, xTrans = log)

pred.svml <- predict(svml.fit, newdata = diabetes_data[-trainRows,])

confusionMatrix(data = pred.svml, 
                reference = diabetes_data$diabetes[-trainRows])
```

```{r svmr}
svmr.grid <- expand.grid(C = exp(seq(-1,4,len=10)),
                         sigma = exp(seq(-8,0,len=10)))

# tunes over both cost and sigma
set.seed(1)             
svmr.fit <- train(diabetes ~ . , 
                  diabetes_data, 
                  subset = trainRows,
                  method = "svmRadialSigma",
                  preProcess = c("center", "scale"),
                  tuneGrid = svmr.grid,
                  trControl = ctrl)

#plot(svmr.fit, highlight = TRUE)

pred.svmr <- predict(svmr.fit, newdata = diabetes_data[-trainRows,])

confusionMatrix(data = pred.svmr, 
                reference = diabetes_data$diabetes[-trainRows])
```



